---

- name: configure dvd region (!)
  become: True
  apt:
    name: regionset
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify: set_region
  when: set_dvd_region == 'yes'

- name: install required system packages
  become: True
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - git
    - python3
    - python3-pip

- name: add PPA repositories
  become: True
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - 'ppa:heyarje/makemkv-beta'
    - 'ppa:stebbins/handbrake-releases'
    - 'ppa:mc3man/xerus-media'

- name: install A.R.M. packages
  become: True
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - makemkv-bin
    - makemkv-oss
    - handbrake-cli
    - libavcodec-extra
    - abcde
    - flac
    - imagemagick
    - glyrc
    - cdparanoia
    - at

- name: install/configure libdvd
  become: True
  apt:
    name: libdvd-pkg
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify: configure_libdvd

- meta: flush_handlers

- name: clone A.R.M. repository
  become: True
  git:
    repo: 'https://github.com/ahnooie/automatic-ripping-machine.git'
    dest: /opt/arm
    force: yes
    update: no

- name: install A.R.M. pip dependencies
  become: True
  pip:
    requirements: '/opt/arm/requirements.txt'
    executable: pip3

- name: Create A.R.M. symbolic links
  become: True
  file:
    src: "/opt/arm/{{ item.filename }}"
    dest: "{{ item.dest }}{{ item.filename }}"
    state: link
  with_items:
    - { filename: '51-automedia.rules', dest: '/lib/udev/rules.d/' }
    - { filename: '.abcde.conf', dest: '/root/' }

- name: Copy A.R.M. systemd files
  become: True
  copy:
    src: /opt/arm/arm@.service
    dest: /etc/systemd/system/arm@.service
    remote_src: yes

- name: Copy A.R.M. configuration templates
  become: True
  template:
    src: "{{ item }}.j2"
    dest: "/opt/arm/{{ item }}"
  with_items:
    - config
    - default.mmcp.xml

- name: Create A.R.M. directories
  become: True
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ arm_path_base }}"
    - "{{ arm_path_raw }}"
    - "{{ arm_path_media }}"

