---
# handlers file for roles/noruro.arm
- name: set_region
  command: "regionset /dev/sr{{ dvd_region}}"
  become: True

- name: configure_libdvd
  command: dpkg-reconfigure -fnotinteractive libdvd-pkg
  become: True

