---
# handlers file for roles/noruro.arm
- name: set_region
  debug:
    msg: "Please run 'regionset /dev/sr0' manually to configure region"
  become: False

- name: configure_libdvd
  command: dpkg-reconfigure -fnotinteractive libdvd-pkg
  become: True

